export enum DocumentTypeEnum {
    INTERNATIONAL_PASSPORT = 'INTERNATIONAL_PASSPORT',
    NATIONAL_PASSPORT = 'NATIONAL_PASSPORT',
    BIRTH_SERTIFICATE = 'BIRTH_SERTIFICATE',
    DIPLOMATIC_PASSPORT = 'DIPLOMATIC_PASSPORT',
    RESIDENT_CARD = 'RESIDENT_CARD',
    NATIONAL_IDENTITY_CARD = 'NATIONAL_IDENTITY_CARD'
}